import { Link } from "react-router-dom";
import type { AlertItem } from "../../types/api";
import { formatDateTime } from "../../lib/utils";
import { GlassPanel } from "../ui/GlassPanel";
import { RiskBadge } from "../ui/RiskBadge";

export function AlertFeed({ alerts }: { alerts: AlertItem[] }) {
  return (
    <GlassPanel title="Recent Alerts" subtitle="Latest district-level warning events">
      <div className="space-y-3">
        {alerts.map((alert) => (
          <div key={alert.id} className="rounded-2xl border border-white/10 bg-white/5 p-4">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="flex items-center gap-2">
                  <h4 className="font-medium text-white">{alert.title ?? "District Risk Alert"}</h4>
                  <RiskBadge level={alert.riskLevel} />
                </div>
                <p className="mt-2 text-sm text-cyan-50/70">{alert.message ?? "Warning generated by the hybrid risk engine."}</p>
                <div className="mt-2 text-xs text-cyan-100/50">{alert.districtName} • {formatDateTime(alert.createdAt)}</div>
              </div>
              <Link to={`/district/${alert.districtId}`} className="rounded-xl border border-cyan-300/15 px-3 py-2 text-xs text-cyan-100">View District</Link>
            </div>
          </div>
        ))}
      </div>
    </GlassPanel>
  );
}
